/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'typing-stats-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./typing-stats-native.android-arm64.node')
          } else {
            nativeBinding = require('typing-stats-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'typing-stats-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./typing-stats-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('typing-stats-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'typing-stats-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./typing-stats-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('typing-stats-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'typing-stats-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./typing-stats-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('typing-stats-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'typing-stats-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./typing-stats-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('typing-stats-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'typing-stats-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./typing-stats-native.darwin-universal.node')
      } else {
        nativeBinding = require('typing-stats-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'typing-stats-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./typing-stats-native.darwin-x64.node')
          } else {
            nativeBinding = require('typing-stats-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'typing-stats-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./typing-stats-native.darwin-arm64.node')
          } else {
            nativeBinding = require('typing-stats-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'typing-stats-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./typing-stats-native.freebsd-x64.node')
      } else {
        nativeBinding = require('typing-stats-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'typing-stats-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./typing-stats-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('typing-stats-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'typing-stats-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./typing-stats-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('typing-stats-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'typing-stats-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./typing-stats-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('typing-stats-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'typing-stats-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./typing-stats-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('typing-stats-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'typing-stats-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./typing-stats-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('typing-stats-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'typing-stats-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./typing-stats-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('typing-stats-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'typing-stats-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./typing-stats-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('typing-stats-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'typing-stats-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./typing-stats-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('typing-stats-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'typing-stats-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./typing-stats-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('typing-stats-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { getMemoryUsage, startMemoryMonitoring, getMemoryStats, resetMemoryMonitoring, getGpuInfo, startGpuMonitoring, getGpuStats, resetGpuMonitoring, addWorkerTask, getWorkerTaskStatus, getWorkerStats, getPendingTaskCount, resetWorkerPool, executeCpuTask, processDataParallel, getSystemInfo, calculateFileHash, startPerformanceMeasurement, endPerformanceMeasurement, calculateDirectorySize, calculateStringSimilarity, validateJson, encodeBase64, decodeBase64, generateUuid, getTimestampString, getEnvVar, getProcessId, getTimestamp, getNativeModuleVersion, initializeNativeModules, cleanupNativeModules, getNativeModuleInfo, isNativeModuleAvailable } = nativeBinding

module.exports.getMemoryUsage = getMemoryUsage
module.exports.startMemoryMonitoring = startMemoryMonitoring
module.exports.getMemoryStats = getMemoryStats
module.exports.resetMemoryMonitoring = resetMemoryMonitoring
module.exports.getGpuInfo = getGpuInfo
module.exports.startGpuMonitoring = startGpuMonitoring
module.exports.getGpuStats = getGpuStats
module.exports.resetGpuMonitoring = resetGpuMonitoring
module.exports.addWorkerTask = addWorkerTask
module.exports.getWorkerTaskStatus = getWorkerTaskStatus
module.exports.getWorkerStats = getWorkerStats
module.exports.getPendingTaskCount = getPendingTaskCount
module.exports.resetWorkerPool = resetWorkerPool
module.exports.executeCpuTask = executeCpuTask
module.exports.processDataParallel = processDataParallel
module.exports.getSystemInfo = getSystemInfo
module.exports.calculateFileHash = calculateFileHash
module.exports.startPerformanceMeasurement = startPerformanceMeasurement
module.exports.endPerformanceMeasurement = endPerformanceMeasurement
module.exports.calculateDirectorySize = calculateDirectorySize
module.exports.calculateStringSimilarity = calculateStringSimilarity
module.exports.validateJson = validateJson
module.exports.encodeBase64 = encodeBase64
module.exports.decodeBase64 = decodeBase64
module.exports.generateUuid = generateUuid
module.exports.getTimestampString = getTimestampString
module.exports.getEnvVar = getEnvVar
module.exports.getProcessId = getProcessId
module.exports.getTimestamp = getTimestamp
module.exports.getNativeModuleVersion = getNativeModuleVersion
module.exports.getSystemInfo = getSystemInfo
module.exports.initializeNativeModules = initializeNativeModules
module.exports.cleanupNativeModules = cleanupNativeModules
module.exports.getNativeModuleInfo = getNativeModuleInfo
module.exports.isNativeModuleAvailable = isNativeModuleAvailable
